export const NIGERIAN_STATES: Record<string, string[]> = {
  Abia: ["Aba", "Onitsha", "Umuahia"],
  Adamawa: ["Mubi", "Yola", "Girei"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
  Bauchi: ["Bauchi", "Dass", "Jada"],
  Bayelsa: ["Yenagoa", "Sagbama", "Ekeremor"],
  Benue: ["Makurdi", "Gboko", "Otukpo"],
  Borno: ["Maiduguri", "Biu", "Dikwa"],
  "Cross River": ["Calabar", "Ogoja", "Obudu"],
  Delta: ["Warri", "Asaba", "Sapele"],
  Ebonyi: ["Abakaliki", "Onueke", "Ezza"],
  Edo: ["Benin City", "Auchi", "Uromi"],
  Ekiti: ["Ado Ekiti", "Ikere", "Aramoko"],
  Enugu: ["Enugu", "Nsukka", "Ozugbo"],
  FCT: ["Abuja", "Gwagwalada", "Kubwa"],
  Gombe: ["Gombe", "Bajoga", "Billiri"],
  Imo: ["Owerri", "Orlu", "Okigwe"],
  Jigawa: ["Dutse", "Hadejia", "Kazaure"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan"],
  Kano: ["Kano", "Kumbotso", "Karaye"],
  Katsina: ["Katsina", "Kankia", "Daura"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri"],
  Kogi: ["Lokoja", "Okene", "Kabba"],
  Kwara: ["Ilorin", "Offa", "Ejidongari"],
  Lagos: ["Lagos", "Lekki", "Ikorodu"],
  Nasarawa: ["Lafia", "Keffi", "Nassarawa Eggon"],
  Niger: ["Minna", "Suleja", "Bida"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu"],
  Ondo: ["Akure", "Owo", "Akungba Akoka"],
  Osun: ["Osogbo", "Ife", "Iwo"],
  Oyo: ["Ibadan", "Oyo", "Ogbomosho"],
  Plateau: ["Jos", "Bukuru", "Pankshin"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Eleme"],
  Sokoto: ["Sokoto", "Gusau", "Argungu"],
  Taraba: ["Jalingo", "Wukari", "Takum"],
  Yobe: ["Damaturu", "Potiskum", "Gasua"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talaka"],
}
