export const NIGERIAN_STATES: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende"],
  Adamawa: ["Yola", "Mubi", "Numan", "Jimeta", "Ganye"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Ibeno"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum"],
  Bayelsa: ["Yenagoa", "Brass", "Sagbama", "Ogbia", "Nembe"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Adoka"],
  Borno: ["Maiduguri", "Biu", "Dikwa", "Bama", "Monguno"],
  "Cross River": ["Calabar", "Ogoja", "Obudu", "Ikom", "Akamkpa"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Ogwashi-Uku"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Edda", "Ishielu"],
  Edo: ["Benin City", "Auchi", "Uromi", "Ekpoma", "Igarra"],
  Ekiti: ["Ado Ekiti", "Ikere", "Ijero", "Ikole", "Oye"],
  Enugu: ["Enugu", "Nsukka", "Agbani", "Awgu", "Udi"],
  FCT: ["Abuja", "Gwagwalada", "Kuye", "Abaji", "Kubwa", "Maitama", "Wuse", "Garki"],
  Gombe: ["Gombe", "Bajoga", "Billiri", "Kaltungo", "Dukku"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Oguta", "Mbaise"],
  Jigawa: ["Dutse", "Hadejia", "Kazaure", "Gumel", "Ringim"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Kagoro", "Zonkwa"],
  Kano: ["Kano", "Rano", "Wudil", "Gaya", "Bichi"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi", "Kankia"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega"],
  Kogi: ["Lokoja", "Okene", "Kabba", "Idah", "Anyigba"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran", "Lafiagi", "Patigi"],
  Lagos: ["Lagos", "Ikeja", "Lekki", "Ikorodu", "Epe", "Badagry", "Surulere", "Victoria Island", "Ajah"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga", "Nasarawa", "Karim Lamido"],
  Niger: ["Minna", "Bida", "Kontagora", "Suleja", "Lapai"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota", "Ilaro"],
  Ondo: ["Akure", "Owo", "Ondo City", "Ore", "Okitipupa"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Iwo", "Ede"],
  Oyo: ["Ibadan", "Oyo City", "Ogbomosho", "Iseyin", "Saki"],
  Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam", "Langtang"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Bonny", "Ahoada", "Okrika", "Degema"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno", "Gwadabawa", "Bodinga"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Gembu", "Takum"],
  Yobe: ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Gummi"],
}
